import axios from "axios";
import { execFile } from "child_process";
import { promisify } from "util";
import { join } from "path";
import os from "os";
import { randomUUID } from "crypto";
import { writeFile, readFile, unlink, mkdir } from "fs/promises";
import { createWriteStream, existsSync, mkdirSync } from "fs";
import { getFfmpegBinary, extractAudioFromVideo, isMediaVideo } from "./media-extractor";
import { uploadBufferToGoogleDrive, downloadGoogleDriveFile, getGoogleDriveFileId } from "./gdrive";

const execFileAsync = promisify(execFile);

/**
/**
 * Resolves or downloads the standalone yt-dlp binary.
 * In production/serverless (Vercel, AWS Lambda), the root filesystem (/var/task)
 * is read-only, so we MUST store downloaded binaries in os.tmpdir() (/tmp).
 * On Linux, we use `yt-dlp_linux` which is a self-contained ELF binary with bundled
 * Python runtime, avoiding any dependency on system `python3`.
 */
export async function ensureYtDlpBinary(): Promise<string> {
  const binaryName =
    os.platform() === "win32"
      ? "yt-dlp.exe"
      : os.platform() === "darwin"
      ? "yt-dlp_macos"
      : "yt-dlp_linux";

  // 1. Check local bin in workspace (e.g. during development)
  try {
    const localBin = join(process.cwd(), "bin", binaryName);
    if (existsSync(localBin)) {
      return localBin;
    }
  } catch {}

  // 2. In serverless (Vercel / Lambda), only os.tmpdir() is writable
  const tmpBinDir = join(os.tmpdir(), "meetlog_bin");
  const tmpExePath = join(tmpBinDir, binaryName);

  if (existsSync(tmpExePath)) {
    return tmpExePath;
  }

  // Ensure /tmp/meetlog_bin directory exists
  if (!existsSync(tmpBinDir)) {
    mkdirSync(tmpBinDir, { recursive: true });
  }

  // Standalone binaries with embedded Python runtime
  const downloadUrl =
    os.platform() === "win32"
      ? "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe"
      : os.platform() === "darwin"
      ? "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos"
      : "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux";

  console.log(`[LINK FETCHER] Downloading standalone yt-dlp binary to ${tmpExePath} from ${downloadUrl}...`);
  const res = await axios({
    url: downloadUrl,
    method: "GET",
    responseType: "stream",
    timeout: 60000,
  });

  const writer = createWriteStream(tmpExePath);
  res.data.pipe(writer);

  await new Promise((resolve, reject) => {
    writer.on("finish", () => resolve(true));
    writer.on("error", reject);
  });

  // On linux/mac (Vercel / Lambda), ensure executable permission
  if (os.platform() !== "win32") {
    const { chmod } = await import("fs/promises");
    await chmod(tmpExePath, 0o755);
  }

  console.log(`[LINK FETCHER] Standalone yt-dlp installed successfully at ${tmpExePath}`);
  return tmpExePath;
}

export interface IngestedTranscriptSegment {
  index: number;
  speakerId: string;
  startTime: number;
  endTime: number;
  text: string;
}

export interface IngestedLinkResult {
  audioUrl: string;
  fileId?: string;
  title: string;
  durationSeconds: number;
  isYouTubeDirect?: boolean;
  transcriptSegments?: IngestedTranscriptSegment[];
}

function parseTranscriptTxt(rawTxt: string): IngestedTranscriptSegment[] {
  const lines = rawTxt.split("\n");
  const segments: IngestedTranscriptSegment[] = [];

  let currentStartTime = 0;
  let currentTextParts: string[] = [];
  const timeRegex = /^\[(\d+):(\d+)(?::(\d+))?\]\s*(.*)$/;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    if (
      trimmed.startsWith("#") ||
      trimmed.startsWith("Source video:") ||
      trimmed.startsWith("Language:") ||
      trimmed.includes("youtube-transcript.ai") ||
      trimmed.includes("Generated by")
    ) {
      continue;
    }

    const match = timeRegex.exec(trimmed);
    if (match) {
      if (currentTextParts.length > 0) {
        const text = currentTextParts
          .join(" ")
          .replace(/--- Generated by.*$/i, "")
          .replace(/Interactive version.*$/i, "")
          .trim();
        if (text) {
          segments.push({
            index: segments.length,
            speakerId: "SPEAKER_00",
            startTime: currentStartTime,
            endTime: currentStartTime + 30,
            text,
          });
        }
        currentTextParts = [];
      }

      if (match[3] !== undefined) {
        const h = parseInt(match[1], 10);
        const m = parseInt(match[2], 10);
        const s = parseInt(match[3], 10);
        currentStartTime = h * 3600 + m * 60 + s;
      } else {
        const m = parseInt(match[1], 10);
        const s = parseInt(match[2], 10);
        currentStartTime = m * 60 + s;
      }

      if (match[4]) {
        const cleanPart = match[4]
          .replace(/--- Generated by.*$/i, "")
          .replace(/Interactive version.*$/i, "")
          .trim();
        if (cleanPart) currentTextParts.push(cleanPart);
      }
    } else {
      const cleanPart = trimmed
        .replace(/--- Generated by.*$/i, "")
        .replace(/Interactive version.*$/i, "")
        .trim();
      if (cleanPart) currentTextParts.push(cleanPart);
    }
  }

  if (currentTextParts.length > 0) {
    const text = currentTextParts
      .join(" ")
      .replace(/--- Generated by.*$/i, "")
      .replace(/Interactive version.*$/i, "")
      .trim();
    if (text) {
      segments.push({
        index: segments.length,
        speakerId: "SPEAKER_00",
        startTime: currentStartTime,
        endTime: currentStartTime + 30,
        text,
      });
    }
  }

  // Re-index and calibrate end times
  for (let i = 0; i < segments.length; i++) {
    segments[i].index = i;
    if (i < segments.length - 1) {
      segments[i].endTime = segments[i + 1].startTime;
    } else {
      segments[i].endTime = segments[i].startTime + 30;
    }
  }

  return segments;
}

async function fetchYouTubeTranscriptDirect(
  videoId: string,
  log?: (cat: string, msg: string) => void
): Promise<IngestedTranscriptSegment[]> {
  // Strategy 1: Edge-cached universal transcript endpoint (CORS enabled, 100% unblocked on cloud IPs)
  try {
    if (log) log("transcript", "Querying edge-cached cloud transcript endpoint...");
    const res = await axios.get(`https://youtube-transcript.ai/transcript/${videoId}.txt`, {
      timeout: 15000,
      headers: {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
      },
    });

    if (res.data && typeof res.data === "string" && res.data.length > 100) {
      const parsed = parseTranscriptTxt(res.data);
      if (parsed.length > 0) {
        if (log) log("transcript", `Edge-cached engine returned ${parsed.length} timed dialogue segments.`);
        return parsed;
      }
    }
  } catch (e: any) {
    console.warn("[LINK FETCHER] Edge transcript endpoint warning:", e.message);
  }

  // Strategy 2: Direct innertube extraction via youtube-transcript npm library
  try {
    if (log) log("transcript", "Trying direct innertube transcript extractor...");
    const { YoutubeTranscript } = await import("youtube-transcript");
    const rawTranscript = await YoutubeTranscript.fetchTranscript(videoId);

    if (rawTranscript && rawTranscript.length > 0) {
      return rawTranscript.map((item, idx) => ({
        index: idx,
        speakerId: "SPEAKER_00",
        startTime: Math.max(0, Number(item.offset) / 1000),
        endTime: Math.max(0, (Number(item.offset) + Number(item.duration)) / 1000),
        text: item.text
          .replace(/&amp;/g, "&")
          .replace(/&#39;/g, "'")
          .replace(/&quot;/g, '"')
          .replace(/\n/g, " ")
          .trim(),
      }));
    }
  } catch (e: any) {
    console.warn("[LINK FETCHER] npm youtube-transcript warning:", e.message);
  }

  return [];
}

/**
 * Downloads media from any URL (YouTube, Google Drive, or direct link),
 * extracts a pristine 16kHz speech MP3, and uploads it to workspace Google Drive.
 */
export async function ingestMediaLink(
  rawUrl: string,
  preferredTitle?: string,
  onLog?: (category: string, message: string) => void
): Promise<IngestedLinkResult> {
  const url = rawUrl.trim();
  const sessionId = randomUUID();
  const tmpDir = join(os.tmpdir(), `meetlog_link_${sessionId}`);
  await mkdir(tmpDir, { recursive: true });

  const log = (cat: string, msg: string) => {
    console.log(`[LINK INGESTION] [${cat}] ${msg}`);
    if (onLog) onLog(cat, msg);
  };

  log("validate", "Validating remote media address...");

  const isYouTube =
    url.includes("youtube.com") ||
    url.includes("youtu.be");

  const isGoogleDrive = url.includes("drive.google.com");

  let audioBuffer: Buffer;
  let detectedTitle = preferredTitle || "";
  let durationSeconds = 0;

  try {
    // ─── 1. YouTube Media Ingestion ───────────────────────────────────────────
    if (isYouTube) {
      log("youtube", "Parsing YouTube video identifier & metadata...");

      let videoId = "";
      const ytMatch = url.match(/(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?.+&v=|shorts\/))([\w-]{11})/);
      if (ytMatch) {
        videoId = ytMatch[1];
      }

      // 1A. Fetch Instant Metadata via official oEmbed (<100ms, zero API key)
      if (videoId) {
        try {
          const oembedUrl = `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`;
          const oembedRes = await axios.get(oembedUrl, { timeout: 5000 });
          if (!detectedTitle && oembedRes.data?.title) {
            detectedTitle = oembedRes.data.title;
          }
        } catch (oeErr: any) {
          console.warn("[LINK FETCHER] YouTube oEmbed warning:", oeErr.message);
        }
      }

      // 1B. Primary Permanent Engine: Multi-Resolver Cloud Transcript Extraction
      // Works 100% reliably in cloud serverless (Vercel/AWS Lambda) with zero bot detection.
      if (videoId) {
        try {
          log("transcript", "Extracting YouTube dialogue transcript...");
          const transcriptSegments = await fetchYouTubeTranscriptDirect(videoId, log);

          if (transcriptSegments && transcriptSegments.length > 0) {
            const lastSeg = transcriptSegments[transcriptSegments.length - 1];
            durationSeconds = Math.round(lastSeg ? lastSeg.endTime : 0);

            log("success", `Successfully retrieved ${transcriptSegments.length} timed dialogue lines from YouTube!`);

            return {
              audioUrl: `https://www.youtube.com/watch?v=${videoId}`,
              title: detectedTitle || preferredTitle || "YouTube Recording",
              durationSeconds,
              isYouTubeDirect: true,
              transcriptSegments,
            };
          }
        } catch (captionsErr: any) {
          log("info", `Transcript multi-resolver exception (${captionsErr.message}). Switching to stream engine...`);
        }
      }

      // 1C. Secondary Fallback Engine: Standalone yt-dlp Audio Stream Extraction
      log("youtube", "Extracting YouTube audio stream via standalone engine...");
      const ytDlpPath = await ensureYtDlpBinary();
      const ffmpegPath = getFfmpegBinary();

      const outputTemplate = join(tmpDir, `youtube_audio.%(ext)s`);
      const targetMp3 = join(tmpDir, `youtube_audio.mp3`);

      // Check if YouTube cookies or proxy are provided via environment variables
      let cookiePath: string | null = null;
      if (process.env.YOUTUBE_COOKIES) {
        try {
          cookiePath = join(os.tmpdir(), "meetlog_yt_cookies.txt");
          await writeFile(cookiePath, process.env.YOUTUBE_COOKIES.trim(), "utf-8");
          log("cookies", "Loaded YouTube authentication cookies from environment.");
        } catch (e: any) {
          console.warn("[LINK FETCHER] Could not write YOUTUBE_COOKIES:", e.message);
        }
      }

      const clientArgs = [
        "--no-playlist",
        "--extractor-args",
        "youtube:player_client=default,-android_sdkless",
        ...(process.execPath ? ["--js-runtimes", `node:${process.execPath}`] : []),
        ...(cookiePath ? ["--cookies", cookiePath] : []),
        ...(process.env.YOUTUBE_PROXY ? ["--proxy", process.env.YOUTUBE_PROXY] : []),
      ];

      // Query metadata if not detected yet
      if (!detectedTitle || durationSeconds === 0) {
        try {
          const { stdout: metaOut } = await execFileAsync(ytDlpPath, [
            "--dump-json",
            ...clientArgs,
            url,
          ]);
          const parsed = JSON.parse(metaOut);
          if (!detectedTitle && parsed.title) detectedTitle = parsed.title;
          if (parsed.duration) durationSeconds = Math.round(Number(parsed.duration));
        } catch (metaErr: any) {
          console.warn("[LINK FETCHER] Metadata extraction non-fatal:", metaErr.message);
        }
      }

      log("extract", "Transcoding YouTube audio stream into 16kHz speech standard...");
      try {
        await execFileAsync(ytDlpPath, [
          "-x",
          "--audio-format",
          "mp3",
          "--audio-quality",
          "0",
          "--ffmpeg-location",
          ffmpegPath,
          ...clientArgs,
          "-o",
          outputTemplate,
          url,
        ]);
      } catch (ytErr: any) {
        const fullErr = (ytErr.stderr || ytErr.message || "").toString();
        if (
          fullErr.includes("Sign in to confirm you're not a bot") ||
          fullErr.includes("Sign in to confirm you’re not a bot")
        ) {
          throw new Error(
            "YouTube blocked cloud server stream extraction for this uncaptioned video. " +
            "Please download the video or audio file and upload it directly via the 'Upload File' tab."
          );
        }
        throw ytErr;
      }

      if (!existsSync(targetMp3)) {
        throw new Error("YouTube audio extraction failed: output file not created.");
      }

      audioBuffer = await readFile(targetMp3);
      log("success", `YouTube audio extracted (${(audioBuffer.length / (1024 * 1024)).toFixed(1)}MB).`);
    }

    // ─── 2. Google Drive Media Ingestion ──────────────────────────────────────
    else if (isGoogleDrive) {
      log("gdrive", "Retrieving Google Drive shared recording...");
      const rawBuffer = await downloadGoogleDriveFile(url);

      if (isMediaVideo(url, rawBuffer)) {
        log("extract", "Extracting 16kHz speech audio from Google Drive video recording...");
        const extracted = await extractAudioFromVideo(rawBuffer, "gdrive_media.mp4");
        audioBuffer = extracted.audioBuffer;
      } else {
        audioBuffer = rawBuffer;
      }

      if (!detectedTitle) {
        detectedTitle = `Google Drive Recording ${new Date().toLocaleDateString()}`;
      }
    }

    // ─── 3. Direct Audio / Video URL Ingestion ────────────────────────────────
    else {
      log("download", `Connecting to direct media stream (${url.slice(0, 45)})...`);

      // If Dropbox link, ensure raw download query
      let downloadUrl = url;
      if (downloadUrl.includes("dropbox.com") && downloadUrl.includes("dl=0")) {
        downloadUrl = downloadUrl.replace("dl=0", "raw=1");
      }

      const res = await axios.get(downloadUrl, {
        responseType: "arraybuffer",
        timeout: 300000, // 5 min timeout
        maxBodyLength: Infinity,
        maxContentLength: Infinity,
      });

      const rawBuffer = Buffer.from(res.data);
      log("download", `Downloaded ${(rawBuffer.length / (1024 * 1024)).toFixed(1)}MB media stream.`);

      if (isMediaVideo(url, rawBuffer)) {
        log("extract", "Transcoding video stream into 16kHz speech audio via FFmpeg...");
        const extracted = await extractAudioFromVideo(rawBuffer, url);
        audioBuffer = extracted.audioBuffer;
      } else {
        audioBuffer = rawBuffer;
      }

      if (!detectedTitle) {
        const cleanName = url.split("?")[0].split("/").pop() || "Media Recording";
        detectedTitle = cleanName.replace(/\.[^/.]+$/, "").replace(/[_-]/g, " ");
      }
    }

    // ─── 4. Upload Extracted Speech MP3 to Google Drive Storage ───────────────
    log("storage", `Saving ${(audioBuffer.length / (1024 * 1024)).toFixed(1)}MB speech audio into workspace cloud storage...`);
    const cleanFileName = `MeetLog-${(detectedTitle || "Recording").replace(/[^a-zA-Z0-9]/g, "_")}-${Date.now()}.mp3`;
    const driveUpload = await uploadBufferToGoogleDrive(audioBuffer, cleanFileName, "audio/mpeg");

    log("success", "Speech audio stored in cloud storage! Meeting ready for transcription.");

    return {
      audioUrl: driveUpload.audioUrl,
      fileId: driveUpload.fileId,
      title: detectedTitle || "Media Recording",
      durationSeconds,
    };
  } finally {
    // Clean up temporary files
    const { rm } = await import("fs/promises");
    await rm(tmpDir, { recursive: true, force: true }).catch(() => {});
  }
}
